In [11]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
     

In [21]:
classes=os.listdir("images/Train")
classes

['Bulbasaur', 'Charmander', 'Pikachu']

In [33]:
print("Training Data :")
for f in classes:
    path="images/Train/"+f
    length=len(os.listdir(path))
    print(f"{f}-{length}")

Training Data :
Bulbasaur-101
Charmander-102
Pikachu-101


In [35]:
print("Training Test :")
for f in classes:
    path="images/Test/"+f
    length=len(os.listdir(path))
    print(f"{f}-{length}")

Training Test :
Bulbasaur-41
Charmander-42
Pikachu-41


# ==== Data Loading  ====

In [64]:
from keras_preprocessing import image

In [72]:
# path="images/Train/Pikachu/300.jpg"
# img=image.load_img(path,target_size=(100,100))
# img=image.img_to_array(img)
# # img.shape
# train_data.append(img) // and that goes for every n images 

(100, 100, 3)

In [146]:

train_data = [] # X
train_labels = [] # Y

for category in classes:
    folder = f"images/Train/{category}"
    for img_name in os .listdir(folder):
        img_path = f"{folder}/{img_name}" #f string
        
        img = image.load_img(img_path, target_size=(100,100))
        img = image.img_to_array(img)
        train_data.append(img)
        train_labels.append(category)

C:\ProgramData\anaconda3\Lib\site-packages\PIL\Image.py:1056: UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images
  warnings.warn(


In [147]:
len(train_labels)

304

In [148]:
len(train_labels)

304

# Data Preprocessing

In [150]:
train_data = np.array(train_data)
train_labels = np.array(train_labels)

In [159]:
train_data = train_data.reshape(len(train_data), 30000)
train_data.shape

(304, 30000)

In [161]:
category2label = {'Pikachu':0, 'Charmander':1, 'Bulbasaur':2}
label2category = {0: 'Pikachu', 1: 'Charmander', 2:'Bulbasaur'}

In [163]:
train_labels = np.array([category2label[label] for label in train_labels])

In [165]:
train_labels.shape

(304,)

In [167]:
from keras.utils import to_categorical
train_labels

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [169]:
train_labels = to_categorical(train_labels) # one hot encoding OHT -- must be done for multi level classification

In [140]:
train_labels.shape

(304, 3)

In [142]:
train_labels[:5]

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

In [173]:
train_labels[-5:]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

# Model Architecture

In [176]:
from keras.layers import Dense
from keras import Sequential

In [ ]:
features = train_data.shape[1]

In [ ]:
model = Sequential()
model.add( Dense(units=512, activation='relu', input_shape=(features,)) )
model.add( Dense(units=256, activation='relu' ) )
model.add( Dense(units=128, activation='relu' ) )
model.add( Dense(units=64, activation='relu' ) )
model.add( Dense(units=3, activation='softmax' ) )

model.compile(optimizer = "adam", loss="categorical_crossentropy", metrics=['accuracy'] )

In [ ]:
model.summary()

In [ ]:
model.fit(train_data, train_labels, batch_size=32, epochs=50)

# Test data

In [179]:
test_data = [] # X
test_labels = [] # Y

for category in classes:
    folder = f"images/Test/{category}"
    for img_name in os.listdir(folder):
        img_path = f"{folder}/{img_name}"
        
        img = image.load_img(img_path, target_size=(100,100))
        img = image.img_to_array(img)
        test_data.append(img)
        test_labels.append(category)

PermissionError: [Errno 13] Permission denied: 'images/Test/Pikachu/.ipynb_checkpoints'

In [ ]:
len(test_data)

In [ ]:
test_data = np.array(test_data)
test_labels = np.array(test_labels)

In [ ]:
test_data.shape

In [ ]:
# test_labels

In [181]:
test_labels = np.array([category2label[label] for label in test_labels])
test_labels = to_categorical(test_labels)
test_labels.shape

(83, 3)

# for any doubt mail at officialgaurav0408@gmail.com 